export const Constants = {
  INTERNAL_SERVER_ERROR: "Caught unhandled exception. Internal Server Error",
  NOT_FOUND: "You are trying to reach some endpoint which doesn't exist in our API. Not Found.",
  BLOCKED_BY_CORS_POLICY: "Blocked by CORS Policy",
  DB_CONNECTION_FAILED: "Failed to connect to database.",
  ALL_FIELDS_ARE_REQUIRED: "All fields are required",
  USER_NOT_FOUND: "There are no users with this username.",
  WRONG_PASSWORD: "Password doesn't match",
  USERNAME_IS_TAKEN: "This username is already taken",
  UNAUTHORIZED: "Unauthorized",
  PASSWORDS_DOESNT_MATCH: "Confirmed password doesn't match new password",
  PASSWORD_CHANGED_SUCCESSFULLY: "Password changed successfully",
  NEW_PASSWORD_AND_OLD_PASSWORD_ARE_THE_SAME: "New password cannot be the same as the old one.",
  ACCOUNT_DELETED_SUCCESSFULLY: "Account deleted successfully",
  ALREADY_IN_CHAT: "You are already in this chat.",
  CHAT_DOESNT_EXIST: "This chat doesn't exist",
  CHAT_JOINED_SUCCESSFULLY: "You joined chat successfully",
  ADMIN_CANT_JOIN_CHAT: "Admin can't join group which is created by him",
  YOU_ARE_NOT_IN_THIS_CHAT: "You are not in this chat",
  CHAT_LEFT_SUCCESSFULLY: "You left the chat successfully",
  CHAT_DELETED_SUCCESSFULLY: "Chat deleted successfully",
  REMOVED_PARTICIPANT_SUCCESSFULLY: "Successfully removed participant from chat",
  ADDED_PARTICIPANT: "Participant added successfully",
  CHAT_RENAMED_SUCCESSFULLY: "Chat renamed successfully",
  RABBITMQ_CONNECTION_FAILED: "Failed to connect to RabbitMQ",
  FAILED_TO_CREATE_QUEUE: "Error while creating queue.",
  CHANNEL_IS_NULL: "RabbitMQ Channel is null",
  FAILED_TO_PRODUCE_MESSAG: "Failed to produce the message"
}